import {
  Company,
  CompanyQuestion,
  CompanyTest,
  MockInterview,
  Role,
} from "@/features/company-prep/types";

export const FALLBACK_ROLES: Role[] = [
  {
    id: "sde",
    name: "SDE",
    skills: ["DSA", "OS", "DBMS", "CN", "System Design"],
  },
  {
    id: "frontend",
    name: "Frontend Engineer",
    skills: ["JavaScript", "TypeScript", "React", "Web Performance", "CSS"],
  },
  {
    id: "backend",
    name: "Backend Engineer",
    skills: ["System Design", "API Design", "DBMS", "Caching", "Distributed Systems"],
  },
  {
    id: "data-analyst",
    name: "Data Analyst",
    skills: ["SQL", "Statistics", "Data Modeling", "Python", "Visualization"],
  },
];

export const FALLBACK_COMPANIES: Company[] = [
  {
    id: "amazon",
    name: "Amazon",
    logoUrl: "/amazon.png",
    roles: ["sde", "frontend", "backend", "data-analyst"],
    frequentTopics: ["arrays", "leadership-principles", "system-design", "sql"],
    description: "High ownership and scalability-focused interviews.",
  },
  {
    id: "google",
    name: "Google",
    logoUrl: "/google.png",
    roles: ["sde", "frontend", "backend", "data-analyst"],
    frequentTopics: ["graphs", "dynamic-programming", "web-performance", "statistics"],
    description: "Strong emphasis on fundamentals and analytical depth.",
  },
  {
    id: "tcs",
    name: "TCS",
    logoUrl: "/tcs.png",
    roles: ["sde", "frontend", "backend", "data-analyst"],
    frequentTopics: ["oops", "dbms", "aptitude", "communication"],
    description: "Balanced fundamentals, aptitude, and practical coding.",
  },
  {
    id: "infosys",
    name: "Infosys",
    logoUrl: "/infosys.png",
    roles: ["sde", "frontend", "backend", "data-analyst"],
    frequentTopics: ["os", "cn", "aptitude", "sql"],
    description: "Core CS + aptitude + scenario-based problem solving.",
  },
  {
    id: "microsoft",
    name: "Microsoft",
    logoUrl: "/microsoft.png",
    roles: ["sde", "frontend", "backend", "data-analyst"],
    frequentTopics: ["trees", "design", "api", "behavioral"],
    description: "Design clarity, coding quality, and collaboration fit.",
  },
];

export const FALLBACK_QUESTIONS: CompanyQuestion[] = [
  {
    id: "q-1",
    companyId: "amazon",
    roleId: "sde",
    type: "coding",
    difficulty: "medium",
    tags: ["arrays", "hashing", "leadership-principles"],
    question: "Given an array, return two indices whose values add up to a target.",
    answer: "Use a hash map to store visited values and indices in O(n).",
    explanation: "For each element x, check if target-x exists in map. If yes, return both indices.",
  },
  {
    id: "q-2",
    companyId: "amazon",
    roleId: "backend",
    type: "theory",
    difficulty: "hard",
    tags: ["system-design", "caching", "api"],
    question: "Design a URL shortening service that supports 10M requests/day.",
    answer: "Use stateless API nodes, key generator, cache, and replicated persistent store.",
    explanation: "Discuss read/write path, caching policy, key collision, and observability.",
  },
  {
    id: "q-3",
    companyId: "amazon",
    roleId: "data-analyst",
    type: "mcq",
    difficulty: "easy",
    tags: ["sql", "joins"],
    question: "Which join returns all rows from left table and matching rows from right table?",
    answer: "LEFT JOIN",
    explanation: "LEFT JOIN preserves all rows in the left table.",
  },
  {
    id: "q-4",
    companyId: "google",
    roleId: "sde",
    type: "coding",
    difficulty: "hard",
    tags: ["graphs", "bfs", "shortest-path"],
    question: "Find the shortest transformation sequence between two words using valid dictionary transitions.",
    answer: "Use BFS over implicit graph where words differ by one character.",
    explanation: "BFS guarantees shortest path in unweighted graph.",
  },
  {
    id: "q-5",
    companyId: "google",
    roleId: "frontend",
    type: "theory",
    difficulty: "medium",
    tags: ["web-performance", "rendering", "react"],
    question: "How would you improve Largest Contentful Paint for a React dashboard?",
    answer: "Prioritize critical CSS, defer non-critical JS, optimize image delivery, and reduce render blocking.",
    explanation: "LCP improves when initial render path is lightweight and content assets are prioritized.",
  },
  {
    id: "q-6",
    companyId: "google",
    roleId: "data-analyst",
    type: "theory",
    difficulty: "medium",
    tags: ["statistics", "experimentation", "ab-testing"],
    question: "How do you define and validate a north-star metric for an A/B test?",
    answer: "Choose a metric tied to product value, with guardrails and statistical significance checks.",
    explanation: "A reliable metric aligns with business impact and avoids local optima.",
  },
  {
    id: "q-7",
    companyId: "tcs",
    roleId: "sde",
    type: "mcq",
    difficulty: "easy",
    tags: ["oops", "inheritance"],
    question: "Which OOP principle allows a class to acquire properties of another class?",
    answer: "Inheritance",
    explanation: "Inheritance enables reuse and extension of behavior.",
  },
  {
    id: "q-8",
    companyId: "tcs",
    roleId: "sde",
    type: "coding",
    difficulty: "easy",
    tags: ["strings", "two-pointers"],
    question: "Check whether a string is a palindrome after removing non-alphanumeric characters.",
    answer: "Use two pointers moving inward while skipping non-alphanumeric chars.",
    explanation: "Two-pointer approach is O(n) and memory efficient.",
  },
  {
    id: "q-9",
    companyId: "tcs",
    roleId: "data-analyst",
    type: "mcq",
    difficulty: "medium",
    tags: ["aptitude", "probability"],
    question: "A fair die is rolled twice. Probability of sum greater than 9?",
    answer: "1/6",
    explanation: "Favorable outcomes: (4,6),(5,5),(5,6),(6,4),(6,5),(6,6) = 6/36.",
  },
  {
    id: "q-10",
    companyId: "infosys",
    roleId: "backend",
    type: "theory",
    difficulty: "medium",
    tags: ["dbms", "indexing", "query-optimization"],
    question: "Why can adding too many indexes degrade write-heavy performance?",
    answer: "Each write must update all affected indexes, increasing write latency.",
    explanation: "Indexes accelerate reads but impose maintenance overhead on writes.",
  },
  {
    id: "q-11",
    companyId: "infosys",
    roleId: "sde",
    type: "theory",
    difficulty: "easy",
    tags: ["os", "process", "thread"],
    question: "Explain process vs thread with one practical example.",
    answer: "Processes isolate memory; threads share process memory for lightweight concurrency.",
    explanation: "Browser tabs as processes and rendering workers as threads is a common example.",
  },
  {
    id: "q-12",
    companyId: "infosys",
    roleId: "frontend",
    type: "coding",
    difficulty: "medium",
    tags: ["javascript", "closures", "async"],
    question: "Implement a debounce utility in JavaScript and explain why it helps in search UIs.",
    answer: "Return a wrapper that resets timeout and invokes callback after delay.",
    explanation: "Debounce reduces redundant network calls and re-renders.",
  },
  {
    id: "q-13",
    companyId: "microsoft",
    roleId: "sde",
    type: "coding",
    difficulty: "medium",
    tags: ["trees", "dfs", "recursion"],
    question: "Validate whether a binary tree is height-balanced.",
    answer: "Post-order traverse and return subtree heights with early break on imbalance.",
    explanation: "Single-pass DFS achieves O(n).",
  },
  {
    id: "q-14",
    companyId: "microsoft",
    roleId: "backend",
    type: "theory",
    difficulty: "hard",
    tags: ["api", "distributed-systems", "idempotency"],
    question: "How do you guarantee idempotency for payment APIs under retries?",
    answer: "Use idempotency keys persisted with request fingerprints and deterministic response replay.",
    explanation: "Ensures duplicate retries do not cause duplicate side effects.",
  },
  {
    id: "q-15",
    companyId: "microsoft",
    roleId: "frontend",
    type: "mcq",
    difficulty: "easy",
    tags: ["react", "state-management"],
    question: "Which hook is best for memoizing expensive computed values in React?",
    answer: "useMemo",
    explanation: "useMemo caches computed output until dependencies change.",
  },
  {
    id: "q-16",
    companyId: "google",
    roleId: "sde",
    type: "coding",
    difficulty: "medium",
    tags: ["dynamic-programming", "arrays"],
    question: "Find maximum subarray sum using linear time approach.",
    answer: "Kadane's algorithm maintains running and global best sums.",
    explanation: "At each index choose extend-or-restart for local optimum.",
  },
  {
    id: "q-17",
    companyId: "amazon",
    roleId: "frontend",
    type: "theory",
    difficulty: "medium",
    tags: ["react", "state-management", "performance"],
    question: "When do you choose local component state over global state?",
    answer: "Prefer local state when scope is isolated and no cross-feature synchronization is needed.",
    explanation: "Reduces complexity and unnecessary global re-renders.",
  },
  {
    id: "q-18",
    companyId: "tcs",
    roleId: "backend",
    type: "mcq",
    difficulty: "easy",
    tags: ["dbms", "normalization"],
    question: "Which normal form removes transitive dependency?",
    answer: "Third Normal Form (3NF)",
    explanation: "3NF removes non-key attributes depending on non-key attributes.",
  },
  {
    id: "q-19",
    companyId: "infosys",
    roleId: "data-analyst",
    type: "theory",
    difficulty: "medium",
    tags: ["sql", "window-functions"],
    question: "Difference between RANK and DENSE_RANK with an example use case.",
    answer: "RANK skips values on ties, DENSE_RANK does not skip ranks.",
    explanation: "Useful for leaderboard and grouped ranking reports.",
  },
  {
    id: "q-20",
    companyId: "microsoft",
    roleId: "data-analyst",
    type: "coding",
    difficulty: "hard",
    tags: ["python", "pandas", "data-cleaning"],
    question: "Design a pipeline to detect and impute outliers in time-series sales data.",
    answer: "Use rolling statistics or robust z-score, then apply model-aware imputation.",
    explanation: "Outlier handling should preserve trend and seasonality.",
  },
  {
    id: "q-21",
    companyId: "google",
    roleId: "backend",
    type: "theory",
    difficulty: "hard",
    tags: ["distributed-systems", "consistency", "replication"],
    question: "How do quorum reads and writes help in eventually consistent systems?",
    answer: "Configure R and W such that R + W > N to improve read freshness.",
    explanation: "Balances latency, availability, and consistency guarantees.",
  },
  {
    id: "q-22",
    companyId: "amazon",
    roleId: "sde",
    type: "theory",
    difficulty: "medium",
    tags: ["behavioral", "leadership-principles"],
    question: "Tell me about a time you disagreed with your team and what happened.",
    answer: "Use STAR format: context, action, measurable outcome, and lesson learned.",
    explanation: "Amazon interviews strongly evaluate ownership and customer obsession behaviors.",
  },
  {
    id: "q-23",
    companyId: "tcs",
    roleId: "sde",
    type: "theory",
    difficulty: "easy",
    tags: ["cn", "http"],
    question: "What is the difference between HTTP and HTTPS?",
    answer: "HTTPS adds TLS encryption, integrity, and server authentication over HTTP.",
    explanation: "TLS protects data in transit and mitigates interception.",
  },
  {
    id: "q-24",
    companyId: "infosys",
    roleId: "sde",
    type: "coding",
    difficulty: "medium",
    tags: ["linked-list", "two-pointers"],
    question: "Detect a cycle in a linked list.",
    answer: "Use Floyd's slow and fast pointer technique.",
    explanation: "If pointers meet, a cycle exists.",
  },
];

export const FALLBACK_MOCK_INTERVIEWS: MockInterview[] = [
  {
    id: "mock-amazon-sde",
    companyId: "amazon",
    roleId: "sde",
    durationMinutes: 35,
    questions: [
      "Explain a project where you reduced latency significantly.",
      "Solve two-sum and discuss trade-offs between approaches.",
      "How would you design an inventory reservation service?",
      "Share an example of handling a major production issue.",
    ],
    evaluationSchema: {
      communicationWeight: 20,
      technicalWeight: 40,
      problemSolvingWeight: 30,
      confidenceWeight: 10,
    },
  },
  {
    id: "mock-google-sde",
    companyId: "google",
    roleId: "sde",
    durationMinutes: 40,
    questions: [
      "Find shortest path in an unweighted graph and analyze complexity.",
      "How would you optimize rendering performance for a large list UI?",
      "Design a rate limiter for a public API.",
      "Explain one hard bug you debugged and your approach.",
    ],
    evaluationSchema: {
      communicationWeight: 15,
      technicalWeight: 45,
      problemSolvingWeight: 30,
      confidenceWeight: 10,
    },
  },
  {
    id: "mock-default",
    companyId: "default",
    roleId: "default",
    durationMinutes: 30,
    questions: [
      "Introduce yourself with your strongest technical project.",
      "Explain one data structure you use often and why.",
      "How do you approach debugging a failing production issue?",
      "What trade-offs do you consider when designing an API?",
    ],
    evaluationSchema: {
      communicationWeight: 25,
      technicalWeight: 35,
      problemSolvingWeight: 30,
      confidenceWeight: 10,
    },
  },
];

export const FALLBACK_TESTS: CompanyTest[] = [
  {
    id: "test-default",
    companyId: "default",
    roleId: "default",
    duration: 75,
    sections: [
      {
        id: "aptitude",
        type: "aptitude",
        title: "Aptitude",
        durationMinutes: 20,
        questions: [],
      },
      {
        id: "coding",
        type: "coding",
        title: "Coding",
        durationMinutes: 30,
        questions: [],
      },
      {
        id: "cs",
        type: "cs",
        title: "Core CS",
        durationMinutes: 25,
        questions: [],
      },
    ],
  },
];
